/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_tags.c"
#include "bar_wintitle.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "floatpos.c"
#include "focusdir.c"
#include "fullscreen.c"
#include "movestack.c"
#include "pertag.c"
#include "push.c"
#include "restartsig.c"
#include "swallow.c"
#include "swapfocus.c"
#include "togglefullscreen.c"
#include "transfer.c"
#include "vanitygaps.c"
#include "zoomswap.c"
#include "xrdb.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_monocle.c"
#include "layout_tile.c"

